"""
Registro completo de los 132 shapefiles organizados por Unidad Regional.
"""
import os
from app.config.settings import BASE_SHAPEFILE_PATH

# ============================================================
# REGISTRO DE SHAPEFILES  (clave → ruta relativa a BASE_SHAPEFILE_PATH)
# ============================================================
_SHAPEFILES: dict[str, str] = {
    # --- SHAPES ESPECIALES ---
    "CARGA_FINCAS": r"CARGA FINCAS - copia1\CARGA FINCAS Copia1\CARGA FINCAS Copia1.shp",
    "CARGA_ABIGEATO": r"CARGA ABIGEATO - copia1\CARGA ABIGEATO - copia1\CARGA ABIGEATO - copia1.shp",

    # --- URC (Unidad Regional Capital) ---
    "URC_CRIA1":  r"CRIA1-URC- 2020\MAPA DELICTUAL CRIA1-URC-2020\MAPA DELICTUAL CRIA1-URC-2020.shp",
    "URC_CRIA2":  r"CRIA2-URC-2020\MAPA DELICTUAL CRIA 2-URC\MAPA DELICTUAL CRIA2-URC-2020.shp",
    "URC_CRIA3":  r"CRIA3-URC-2020\MAPA DELICTUAL CRIA3-URC-2020\MAPA DELICTUAL CRIA3-URC-2020.shp",
    "URC_CRIA4":  r"CRIA4-URC-2020\MAPA DELICTUAL CRIA4-URC-2020\MAPA DELICTUAL CRIA4-URC-2020.shp",
    "URC_CRIA5":  r"CRIA5-URC-2020\MAPA DELICTUAL CRIA5-URC-2020\MAPA DELICTUAL CRIA5-URC-2020.shp",
    "URC_CRIA6":  r"CRIA6-URC-2020\MAPA DELICTUAL CRIA6-URC-2020\MAPA DELICTUAL CRIA6-URC-2020.shp",
    "URC_CRIA7":  r"CRIA7-URC-2020\MAPA DELICTUAL CRIA7-URC-2019\MAPA DELICTUAL CRIA7-URC-2019.shp",
    "URC_CRIA8":  r"CRIA8-URC-2020\MAPA DELICTUAL CRIA8-URC-2020\MAPA DELICTUAL CRIA8-URC-2020.shp",
    "URC_CRIA9":  r"CRIA9-URC-2020\MAPA DELICTUAL CRIA9-URC-2020\MAPA DELICTUAL CRIA9-URC-2020.shp",
    "URC_CRIA10": r"CRIA10-URC-2020\MAPA DELICTUAL CRIA10-URC-2020\MAPA DELICTUAL CRIA10-URC-2020.shp",
    "URC_CRIA11": r"CRIA11-URC-2020\MAPA DELICTUAL CRIA11-URC-2020\MAPA DELICTUAL CRIA11-URC-2020.shp",
    "URC_CRIA12": r"CRIA12-URC-2020\MAPA DELICTUAL CRIA12-URC-2020\MAPA DELICTUAL CRIA12-URC-2020.shp",
    "URC_CRIA13": r"CRIA13-URC-2020\MAPA DELICTUAL CRIA13-URC-2020\MAPA DELICTUAL CRIA13-URC-2020.shp",
    "URC_CRIA14": r"CRIA14-URC-2020\MAPA DELICTUAL CRIA14-URC-2020\MAPA DELICTUAL CRIA14-URC-2020.shp",
    "URC_CRIA15": r"CRIA15-URC-2020\MAPA DELICTUAL CRIA15-URC-2020\MAPA DELICTUAL CRIA15-URC-2020.shp",

    # --- URE (Unidad Regional Este) ---
    "URE_BURRUYACU":       r"CRIA BURRUYACU-URE-2024\MAPA DELICTUAL CRIA BURRUYACU-URE\MAPA DELICTUAL CRIA BURRUYACU-URE.shp",
    "URE_BANDA_RIO_SALI":  r"CRIA BANDA DEL RIO SALI-URE\MAPA DELICTUAL CRIA BANDA DEL RIO SALI - URE\MAPA DELICTUAL CRIA BANDA DEL RIO SALI - URE.shp",
    "URE_ALDERETES":       r"CRIA ALDERETES-URE\MAPA DELICTUAL CRIA ALDERETES-URE\MAPA DELICTUAL CRIA ALDERETES-URE.shp",
    "URE_LASTENIA":        r"CRIA LASTENIA-URE\MAPA DELICTUAL CRIA LASTENIA - URE\MAPA DELICTUAL CRIA LASTENIA - URE.shp",
    "URE_GUEMES":          r"CRIA GUEMES-URE\MAPA DELICTUAL CRIA GUEMES-URE-2020\MAPA DELICTUAL CRIA GUEMES-URE-2020.shp",
    "URE_LAS_CEJAS":       r"CRIA LAS CEJAS-URE\MAPA DELICTUAL CRIA LAS CEJAS-URE\MAPA DELICTUAL CRIA LAS CEJAS-URE.shp",
    "URE_BELLA_VISTA":     r"CRIA BELLA VISTA-URE\MAPA DELICTUAL CRIA BELLA VISTA-URE\MAPA DELICTUAL CRIA BELLA VISTA-URE.shp",
    "URE_COLOMBRES":       r"CRIA COLOMBRES-URE\MAPA DELICTUAL CRIA COLOMBRES-URE\MAPA DELICTUAL CRIA COLOMBRES-URE.shp",
    "URE_EL_CHANIAR":      r"CRIA EL CHAÑAR-URE\MAPA DELICTUAL CRIA EL CHAÑAR-URE\MAPA DELICTUAL CRIA EL CHAÑAR-URE.shp",
    "URE_GARMENDIA":       r"CRIA GARMENDIA-URE-2024\MAPA DELICTUAL CRIA GARMENDIA-URE\MAPA DELICTUAL CRIA GARMENDIA-URE.shp",
    "URE_CHILCAS":         r"CRIA CHILCAS-URE-2024\MAPA DELICTUAL CRIA CHILCAS-URE\MAPA DELICTUAL CRIA CHILCAS-URE.shp",
    "URE_RANCHILLOS":      r"CRIA RANCHILLOS-URE\MAPA DELICTUAL CRIA DE RANCHILLOS-URE\MAPA DELICTUAL CRIA DE RANCHILLOS-URE.shp",
    "URE_LOS_RALOS":       r"CRIA LOS RALOS-URE\MAPA DELICTUAL CRIA LOS RALOS-URE\MAPA DELICTUAL CRIA LOS RALOS-URE.shp",
    "URE_DELFIN_GALLO":    r"CRIA DELFIN GALLO-URE\MAPA DELICTUAL CRIA DELFIN GALLO-URE\MAPA DELICTUAL CRIA DELFIN GALLO-URE.shp",
    "URE_LA_FLORIDA":      r"CRIA LA FLORIDA-URE\MAPA DELICTUAL CRIA LA FLORIDA-URE\MAPA DELICTUAL CRIA LA FLORIDA-URE.shp",
    "URE_SAN_ANDRES":      r"CRIA SAN ANDRES-URE\MAPA DELICTUAL CRIA SAN ANDRES-URE\MAPA DELICTUAL CRIA SAN ANDRES-URE.shp",
    "URE_EL_BRACHO":       r"CRIA EL BRACHO-URE\MAPA DELICTUAL CRIA EL BRACHO-URE\MAPA DELICTUAL CRIA EL BRACHO-URE.shp",
    "URE_POZO_ALTO":       r"CRIA POZO DEL ALTO-URE\MAPA DELICTUAL CRIA POZO DEL ALTO-URE\MAPA DELICTUAL CRIA POZO DEL ALTO-URE.shp",
    "URE_EL_NARANJO":      r"CRIA EL NARANJO-URE-2024\MAPA DELICTUAL CRIA EL NARANJO-URE\MAPA DELICTUAL CRIA EL NARANJO-URE.shp",
    "URE_PIEDRABUENA":     r"CRIA GOB PIEDRABUENA-URE-2024\MAPA DELICTUAL CRIA GOB PIEDRABUENA-URE\MAPA DELICTUAL CRIA GOB PIEDRABUENA-URE.shp",
    "URE_PADRE_MONTI":     r"CRIA VILLA PADRE MONTI-URE-2024\MAPA DELICTUAL CRIA VILLA PADRE MONTI-URE\MAPA DELICTUAL CRIA VILLA PADRE MONTI-URE.shp",
    "URE_EL_TIMBO":        r"CRIA EL TIMBO-URE\MAPA DELICTUAL CRIA EL TIMBO-URE\MAPA DELICTUAL CRIA EL TIMBO-URE.shp",
    "URE_LA_RAMADA":       r"CRIA LA RAMADA-URE-2024\MAPA DELICTUAL CRIA LA RAMADA-URE\MAPA DELICTUAL CRIA LA RAMADA-URE.shp",
    "URE_EL_CAJON":        r"CRIA EL CAJON-URE-2024\MAPA DELICTUAL CRIA EL CAJON-URE\MAPA DELICTUAL CRIA EL CAJON-URE.shp",
    "URE_VILLA_B_ARAOZ":   r"CRIA VILLA BENJAMIN ARAOZ-URE-2024\MAPA DELICTUAL CRIA VILLA BENJAMIN ARAOZ-URE\MAPA DELICTUAL CRIA VILLA BENJAMIN ARAOZ-URE.shp",
    "URE_EL_PUESTITO":     r"CRIA EL PUESTITO-URE-2024\MAPA DELICTUAL CRIA EL PUESTITO-URE\MAPA DELICTUAL CRIA EL PUESTITO-URE.shp",
    "URE_7_DE_ABRIL":      r"CRIA 7 DE ABRIL-URE-2024\MAPA DELICTUAL CRIA 7 DE ABRIL-URE\MAPA DELICTUAL CRIA 7 DE ABRIL-URE.shp",
    "URE_ROMERA_POZO":     r"CRIA ROMERA POZO-URE\MAPA DELICTUAL CRIA ROMERA POZO-URE\MAPA DELICTUAL CRIA ROMERA POZO-URE.shp",
    "URE_STA_ROSA_LEALES": r"CRIA SANTA ROSA DE LEALES-URE\MAPA DELICTUAL CRIA SANTA ROSA DE LEALES-URE\MAPA DELICTUAL CRIA SANTA ROSA DE LEALES-URE.shp",
    "URE_QUILMES":         r"CRIA QUILMES-URE\MAPA DELICTUAL CRIA QUILMES-URE\MAPA DELICTUAL CRIA QUILMES-URE.shp",
    "URE_INGENIO_LEALES":  r"CRIA INGENIO LEALES-URE\MAPA DELICTUAL CRIA INGENIO LEALES-URE\MAPA DELICTUAL CRIA INGENIO LEALES-URE.shp",
    "URE_LOS_SUELDOS":     r"CRIA LOS SUELDOS-URE\MAPA DELICTUAL CRIA LOS SUELDOS-URE\MAPA DELICTUAL CRIA LOS SUELDOS-URE.shp",
    "URE_ESTACION_ARAOZ":  r"CRIA ESTACION ARAOZ-URE-2024\MAPA DELICTUAL CRIA ESTACION ARAOZ-URE\MAPA DELICTUAL CRIA ESTACION ARAOZ-URE.shp",
    "URE_VILLA_LEALES":    r"CRIA VILLA DE LEALES-URE\MAPA DELICTUAL CRIA VILLA DE LEALES-URE\MAPA DELICTUAL CRIA VILLA DE LEALES-URE.shp",
    "URE_RIO_COLORADO":    r"CRIA RIO COLORADO-URE\MAPA DELICTUAL CRIA RIO COLORADO-URE\MAPA DELICTUAL CRIA RIO COLORADO-URE.shp",
    "URE_ESQUINA":         r"CRIA ESQUINA-URE\SHAPES_CRIA ESQUINA-URE\MAPA DELICTUAL CRIA ESQUINA-URE.shp",
    "URE_MANCOPA":         r"CRIA MANCOPA-URE\MAPA DELICTUAL CRIA MANCOPA - URE\MAPA DELICTUAL CRIA MANCOPA - URE.shp",
    "URE_AGUA_DULCE":      r"CRIA AGUA DULCE-URE-2024\MAPA DELICTUAL CRIA AGUA DULCE-URE\MAPA DELICTUAL CRIA AGUA DULCE-URE.shp",
    "URE_LOS_GOMES":       r"CRIA LOS GOMES-URE\MAPA DELICTUAL CRIA LOS GOMES-URE\MAPA DELICTUAL CRIA LOS GOMES-URE.shp",
    "URE_LOS_PUESTOS":     r"CRIA LOS PUESTOS-URE\MAPA DELICTUAL CRIA LOS PUESTOS-URE\MAPA DELICTUAL CRIA LOS PUESTOS-URE.shp",
    "URE_LOS_HERRERA":     r"CRIA LOS HERRERA-URE\MAPA DELICTUAL CRIA LOS HERRERA-URE\MAPA DELICTUAL CRIA LOS HERRERA-URE.shp",
    "URE_EL_MOJON":        r"CRIA EL MOJON-URE-2024\MAPA DELICTUAL CRIA EL MOJON-URE\MAPA DELICTUAL CRIA EL MOJON-URE.shp",
    "URE_CAMPO_QUIMIL":    r"CRIA CAMPO QUIMIL-URE-2024\MAPA DELICTUAL CRIA CAMPO QUIMIL-URE\MAPA DELICTUAL CRIA CAMPO QUIMIL-URE.shp",
    "URE_LOS_BULACIOS":    r"CRIA LOS BULACIOS-URE\MAPA DELICTUAL CRIA LOS BULACIOS-URE\MAPA DELICTUAL CRIA LOS BULACIOS-URE.shp",

    # --- URO (Unidad Regional Oeste) ---
    "URO_TAFI_VALLE":      r"CRIA TAFI DEL VALLE-URO\MAPA DELICTUAL CRIA  TAFI DEL VALLE-URO\MAPA DELICTUAL CRIA TAFI DEL VALLE-URO.shp",
    "URO_EL_MOLLAR":       r"CRIA EL MOLLAR-URO\MAPA DELICTUAL CRIA EL MOLLAR-URO\MAPA DELICTUAL CRIA EL MOLLAR-URO.shp",
    "URO_AMAICHA":         r"CRIA AMAICHA DEL VALLE-URO\MAPA DELICTUAL CRIA  AMAICHA DEL VALLE-URO\MAPA DELICTUAL CRIA AMAICHA DEL VALLE-URO.shp",
    "URO_COLALAO":         r"CRIA COLALAO DEL VALLE-URO-2024\MAPA DELICTUAL CRIA COLALAO DEL VALLE-URO\MAPA DELICTUAL CRIA COLALAO DEL VALLE-URO.shp",
    "URO_LULES":           r"CRIA LULES-URO\MAPA DELICTUAL CRIA LULES-URO\MAPA DELICTUAL CRIA LULES-URO.shp",
    "URO_LA_REDUCCION":    r"CRIA LA REDUCCION-URO\MAPA DELICTUAL CRIA LA REDUCCION-URO\MAPA DELICTUAL CRIA LA REDUCCION-URO.shp",
    "URO_EL_MANANTIAL":    r"CRIA EL MANANTIAL-URO\MAPA DELICTUAL CRIA EL MANANTIAL-URO\MAPA DELICTUAL CRIA EL MANANTIAL-URO.shp",
    "URO_SAN_PABLO":       r"CRIA SAN PABLO-URO\MAPA DELICTUAL CRIA SAN PABLO-URO-2020\MAPA DELICTUAL CRIA SAN PABLO-URO-2020.shp",
    "URO_VILLA_NOUGUES":   r"CRIA VILLA NOUGUES-URO\MAPA DELICTUAL CRIA VILLA NOUGUES-URO\MAPA DELICTUAL CRIA VILLA NOUGUES-URO.shp",
    "URO_LOS_AGUIRRE":     r"CRIA LOS AGUIRRE-URO\MAPA DELICTUAL CRIA LOS AGUIRRE-URO-2020\MAPA DELICTUAL CRIA LOS AGUIRRE-URO-2020.shp",
    "URO_FAMAILLA":        r"CRIA FAMAILLA-URO\MAPA DELICTUAL CRIA FAMAILLA-URO\MAPA DELICTUAL CRIA FAMAILLA-URO.shp",
    "URO_TTE_BERDINA":     r"CRIA TENIENTE BERDINA-URO-2024\MAPA DELICTUAL CRIA TENIENTE BERDINA-URO\MAPA DELICTUAL CRIA TENIENTE BERDINA-URO.shp",
    "URO_MONTEROS":        r"CRIA MONTEROS-URO\MAPA DELICTUAL CRIA MONTEROS-URO\MAPA DELICTUAL CRIA MONTEROS-URO.shp",
    "URO_SANTA_LUCIA":     r"CRIA SANTA LUCIA-URO-2024\MAPA DELICTUAL CRIA SANTA LUCIA-URO\MAPA DELICTUAL CRIA SANTA LUCIA-URO.shp",
    "URO_ACHERAL":         r"CRIA ACHERAL-URO-2024\MAPA DELICTUAL CRIA ACHERAL-URO\MAPA DELICTUAL CRIA ACHERAL-URO.shp",
    "URO_RIO_SECO":        r"CRIA RIO SECO-URO-2024\MAPA DELICTUAL CRIA RIO SECO-URO\MAPA DELICTUAL CRIA RIO SECO-URO.shp",
    "URO_VILLA_QUINTEROS": r"CRIA VILLA QUINTEROS-URO\MAPA DELICTUAL CRIA VILLA QUINTEROS-URO\MAPA DELICTUAL CRIA VILLA QUINTEROS-URO.shp",
    "URO_LEON_ROUGES":     r"CRIA LEON ROUGES-URO-2024\MAPA DELICTUAL CRIA LEON ROUGES-URO\MAPA DELICTUAL CRIA LEON ROUGES-URO.shp",
    "URO_CAPITAN_CACERES": r"CRIA CAPITAN CACERES-URO-2024\MAPA DELICTUAL CRIA CAPITAN CACERES-URO\MAPA DELICTUAL CRIA CAPITAN CACERES-URO.shp",
    "URO_LOS_SOSA":        r"CRIA LOS SOSA Y SOLDADO MALDONADO-URO-2024\MAPA DELICTUAL CRIA LOS SOSA Y SOLDADO MALDONADO-URO\MAPA DELICTUAL CRIA LOS SOSA Y SOLDADO MALDONADO-URO.shp",
    "URO_AMBERES":         r"CRIA AMBERES-URO-2024\MAPA DELICTUAL CRIA AMBERES-URO\MAPA DELICTUAL CRIA AMBERES-URO.shp",
    "URO_SGTO_MOYA":       r"CRIA SARGENTO MOYA-URO-2024\MAPA DELICTUAL CRIA SARGENTO MOYA-URO\MAPA DELICTUAL CRIA SARGENTO MOYA-URO.shp",

    # --- URS (Unidad Regional Sur) ---
    "URS_CONCEPCION":      r"CRIA CONCEPCION-URS\MAPA DELICTUAL CRIA CONCEPCION-URS\MAPA DELICTUAL CRIA CONCEPCION-URS.shp",
    "URS_ALTO_VERDE":      r"CRIA ALTO VERDE-URS\CRIA ALTO VERDE-URS\CRIA ALTO VERDE-URS.shp",
    "URS_ARCADIA":         r"CRIA ARCADIA-URS-2024\MAPA DELICTUAL CRIA ARCADIA-URS\MAPA DELICTUAL CRIA ARCADIA-URS.shp",
    "URS_ALPACHIRI":       r"CRIA ALPACHIRI-URS-2024\MAPA DELICTUAL CRIA ALPACHIRI URS\MAPA DELICTUAL CRIA ALPACHIRI URS.shp",
    "URS_MEDINAS":         r"CRIA MEDINAS -URS-2024\MAPA DELICTUAL CRIA MEDINAS URS\MAPA DELICTUAL CRIA MEDINAS URS.shp",
    "URS_LA_TRINIDAD":     r"CRIA LA TRINIDAD-URS\MAPA DELICTUAL CRIA LA TRINIDAD-URS\MAPA DELICTUAL CRIA LA TRINIDAD-URS.shp",
    "URS_AGUILARES":       r"CRIA AGUILARES-URS\MAPA DELICTUAL CRIA AGUILARES-URS\MAPA DELICTUAL CRIA AGUILARES-URS.shp",
    "URS_EL_POLEAR":       r"DESTACAMENTO EL POLEAR URS-2024\MAPA DELICTUAL DESTACAMENTO EL POLEAR -URS\MAPA DELICTUAL DESTACAMENTO EL POLEAR  URS.shp",
    "URS_SANTA_ANA":       r"CRIA SANTA ANA -URS-2024\MAPA DELICTUAL CRIA SANTA ANA URS\MAPA DELICTUAL CRIA SANTA ANA-URS.shp",
    "URS_LOS_SARMIENTOS":  r"CRIA LOS SARMIENTOS-URS\MAPA DELICTUAL CRIA LOS SARMIENTOS-URS\MAPA DELICTUAL CRIA LOS SARMIENTOS-URS.shp",
    "URS_STA_CRUZ_TUNA":   r"CRIA DE SANTA CRUZ Y LA TUNA-URS-2024\MAPA DELICTUAL CRIA DE SANTA CRUZ Y LA TUNA-URS\MAPA DELICTUAL CRIA DE SANTA CRUZ Y LA TUNA-URS.shp",
    "URS_MONTEAGUDO":      r"CRIA DE MONTEAGUDO-URS-2024\MAPA DELICTUAL CRIA DE MONTEAGUDO-URS\MAPA DELICTUAL CRIA DE MONTEAGUDO-URS.shp",
    "URS_CHICLIGASTA":     r"CRIA DE VILLA DE CHICLIGASTA-URS-2024\MAPA DELICTUAL CRIA DE VILLA DE CHICLIGASTA-URS\MAPA DELICTUAL CRIA DE VILLA DE CHICLIGASTA-URS.shp",
    "URS_GRANEROS":        r"CRIA GRANEROS-URS\MAPA DELICTUAL CRIA GRANEROS-URS\MAPA DELICTUAL CRIA GRANEROS-URS.shp",
    "URS_ATAHONA":         r"CRIA ATAHONA-URS-2024\MAPA DELICTUAL CRIA ATAHONA-URS\MAPA DELICTUAL CRIA ATAHONA-URS.shp",
    "URS_SIMOCA":          r"CRIA SIMOCA-URS\MAPA DELICTUAL CRIA SIMOCA-URS\MAPA DELICTUAL CRIA SIMOCA-URS.shp",
    "URS_TACO_RALO":       r"CRIA DE TACO RALO-URS-2024\MAPA DELICTUAL CRIA DE TACO RALO-URS\MAPA DELICTUAL CRIA DE TACO RALO-URS.shp",
    "URS_VILLA_BELGRANO":  r"CRIA DE VILLA BELGRANO-URS-2024\MAPA DELICTUAL CRIA DE VILLA BELGRANO-URS\MAPA DELICTUAL CRIA DE VILLA BELGRANO-URS.shp",
    "URS_LAMADRID":        r"CRIA DE LAMADRID-URS-2024\MAPA DELICTUAL CRIA DE LAMADRID-URS\MAPA DELICTUAL CRIA DE LAMADRID-URS.shp",
    "URS_ALBERDI":         r"CRIA ALBERDI-URS\MAPA DELICTUAL CRIA CRIA ALBERDI-URS\MAPA DELICTUAL CRIA ALBERDI-URS.shp",
    "URS_ESCABA":          r"CRIA ESCABA-URS\MAPA DELICTUAL CRIA ESCABA-URS\MAPA DELICTUAL CRIA ESCABA-URS.shp",
    "URS_LA_INVERNADA":    r"CRIA LA INVERNADA-URS-2024\MAPA DELICTUAL CRIA LA INVERNADA-URS\MAPA DELICTUAL CRIA LA INVERNADA-URS.shp",
    "URS_LA_COCHA":        r"CRIA LA COCHA-URS\MAPA DELICTUAL CRIA LA COCHA-URS\MAPA DELICTUAL CRIA LA COCHA-URS.shp",
    "URS_SAN_IGNACIO":     r"CRIA SAN IGNACIO-URS-2024\MAPA DELICTUAL CRIA SAN IGNACIO-URS\MAPA DELICTUAL CRIA SAN IGNACIO-URS.shp",
    "URS_RUMIPUNCO":       r"CRIA RUMIPUNCO-URS-2024\MAPA DELICTUAL CRIA RUMIPUNCO-URS\MAPA DELICTUAL CRIA RUMIPUNCO-URS.shp",
    "URS_ARBOLES_GRANDES": r"CRIA ARBOLES GRANDES-URS-2024\MAPA DELICTUAL CRIA ARBOLES GRANDES-URS\MAPA DELICTUAL CRIA ARBOLES GRANDES-URS.shp",
    "URS_HUASA_PAMPA":     r"CRIA DE HUASA PAMPA-URS-2024\MAPA DELICTUAL CRIA DE HUASA PAMPA-URS\MAPA DELICTUAL CRIA DE HUASA PAMPA-URS.shp",

    # --- URN (Unidad Regional Norte) ---
    "URN_TRANCAS":         r"CRIA TRANCAS -URN\MAPA DELICTUAL CRIA TRANCAS-URN\MAPA DELICTUAL CRIA TRANCAS-URN.shp",
    "URN_CHUSCHA":         r"CRIA CHUSCHA-URN-2024\MAPA DELICTUAL CRIA CHUSCHA\MAPA DELICTUAL CRIA DE CHUSCHA.shp",
    "URN_CHOROMORO":       r"CRIA CHOROMORO-URN-2024\MAPA DELICTUAL CRIA CHOROMORO\MAPA DELICTUAL CRIA DE CHOROMORO.shp",
    "URN_VIPOS":           r"CRIA VIPOS-URN\MAPA DELICTUAL CRIA VIPOS-URN\MAPA DELICTUAL CRIA VIPOS-URN.shp",
    "URN_TAPIA":           r"SUBCOMISARIA DE TAPIA-URN-2024\MAPA DELICTUAL SUBCOMISARIA DE TAPIA-URN\MAPA DELICTUAL SUBCOMISARIA DE TAPIA-URN.shp",
    "URN_SAN_PEDRO":       r"CRIA SAN PEDRO-URN\MAPA DELICTUAL CRIA SAN PEDRO-URN\MAPA DELICTUAL CRIA SAN PEDRO-URN.shp",
    "URN_YERBA_BUENA":     r"CRIA YERBA BUENA-URN\SHAPES_CRIA YERBA BUENA-URN\MAPA DELICTUAL CRIA YERBA BUENA-URN.shp",
    "URN_MARTI_COLL":      r"CRIA MARTI COLL-URN\SHAPES_CRIA MARTI COLL-URN\MAPA DELICTUAL CRIA MARTI COLL-URN.shp",
    "URN_SAN_JOSE":        r"CRIA SAN JOSE-URN\MAPA DELICTUAL CRIA SAN JOSE-URN-2020\MAPA DELICTUAL CRIA SAN JOSE-URN-2020.shp",
    "URN_EL_CORTE":        r"CRIA EL CORTE-URN\MAPA DELICTUAL CRIA EL CORTE-URN\MAPA DELICTUAL CRIA EL CORTE-URN.shp",
    "URN_SAN_JAVIER":      r"CRIA SAN JAVIER-URN\MAPA DELICTUAL CRIA SAN JAVIER-URN\MAPA DELICTUAL CRIA SAN JAVIER-URN.shp",
    "URN_VILLA_CARMELA":   r"CRIA VILLA CARMELA-URN-URC-2020\MAPA DELICTUAL CRIA VILLA CARMELA-URN-2020\MAPA DELICTUAL CRIA VILLA CARMELA.shp",
    "URN_RACO":            r"CRIA RACO-URN\MAPA DELICTUAL CRIA RACO-URN\MAPA DELICTUAL CRIA RACO-URN.shp",
    "URN_LOS_NOGALES":     r"CRIA LOS NOGALES-URN\MAPA DELICTUAL CRIA LOS NOGALES-URN\MAPA DELICTUAL CRIA LOS NOGALES-URN.shp",
    "URN_EL_CADILLAL":     r"CRIA EL CADILLAL-URN\MAPA DELICTUAL CRIA EL CADILLAL-URN\MAPA DELICTUAL CRIA EL CADILLAL-URN.shp",
    "URN_LAS_TALITAS":     r"CRIA LAS TALITAS-URN\MAPA DELICTUAL CRIA LAS TALITAS-URN\MAPA DELICTUAL CRIA LAS TALITAS-URN.shp",
    "URN_MARIANO_MORENO":  r"CRIA VILLA MARIANO MORENO-URN\MAPA DELICTUAL CRIA VILLA MARIANO MORENO-URN\MAPA DELICTUAL CRIA VILLA MARIANO MORENO-URN.shp",
    "URN_EL_COLMENAR":     r"CRIA EL COLMENAR-URN\MAPA DELICTUAL CRIA EL COLMENAR-URN\MAPA DELICTUAL CRIA VILLA EL COLMENAR URN.shp",
    "URN_LOS_POCITOS":     r"CRIA LOS POCITOS-URN\MAPA DELICTUAL CRIA LOS POCITOS-URN\MAPA DELICTUAL CRIA LOS POCITOS-URN.shp",
    "URN_LOMAS_TAFI":      r"CRIA LOMAS DE TAFI-URN\SHAPES_CRIA_LOMAS_DE_TAFI-URN\MAPA DELICTUAL CRIA LOMAS DE TAFI-URN.shp",
    "URN_VILLA_OBRERA":    r"CRIA VILLA OBRERA--URN\MAPA DELICTUAL CRIA VILLA OBRERA-URN\MAPA DELICTUAL CRIA VILLA OBRERA-URN.shp",
    "URN_TAFI_VIEJO_CENTRO": r"CRIA TAFI VIEJO CENTRO-URN\MAPA DELICTUAL CRIA TAFI VIEJO CENTRO-URN\MAPA DELICTUAL CRIA TAFI VIEJO CENTRO-URN.shp",
}


# ============================================================
# FUNCIONES DE CONSULTA
# ============================================================

def get_full_path(key: str) -> str:
    """Devuelve la ruta absoluta de un shapefile dado su clave."""
    rel = _SHAPEFILES.get(key)
    if rel is None:
        raise KeyError(f"Shapefile '{key}' no encontrado en el registro.")
    return os.path.join(BASE_SHAPEFILE_PATH, rel)


def get_all_keys() -> list[str]:
    """Devuelve todas las claves del registro."""
    return list(_SHAPEFILES.keys())


def get_keys_by_ur(ur_prefix: str) -> list[str]:
    """
    Devuelve las claves cuyo nombre comienza con un prefijo de Unidad Regional.
    Ejemplo: get_keys_by_ur("URC") → ["URC_CRIA1", "URC_CRIA2", ...]
    """
    prefix = ur_prefix.upper() + "_"
    return [k for k in _SHAPEFILES if k.startswith(prefix)]


def get_ur_from_key(key: str) -> str:
    """
    Extrae el código de Unidad Regional de una clave.
    Ejemplo: "URN_TRANCAS" → "URN"
    """
    if key.startswith("CARGA_"):
        return "ESPECIAL"
    return key.split("_")[0]


def get_all_by_ur() -> dict[str, list[str]]:
    """Agrupa todas las claves por Unidad Regional."""
    from collections import defaultdict
    result: dict[str, list[str]] = defaultdict(list)
    for key in _SHAPEFILES:
        ur = get_ur_from_key(key)
        result[ur].append(key)
    return dict(result)
